### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by drewsymo** [hoaproject/Ruler#114]
Hi!

Just wondering if this library is still mantianed?

Seems the website isn't loading: https://hoa-project.net/

**Comment by vonglasow** [comment]
@drewsymo yes this library is still maintained, we are investigating about the website not responding.
Thanks for the report

**Comment by Hywan** [comment]
Hello,

Our Web server is down. We are looking actively to restore it :-).

**Comment by Hywan** [comment]
@drewsymo Fixed! Thanks for your patience and the reporting, and sorry for the issue…
