### ISSUE TITLE
I want to get all variable appear in string rule. Example "q1 != 8 and q2 != 12", i need ["q1", "q2"] How ? 

### ISSUE THREAD

**Issue by vucongduy1902** [hoaproject/Ruler#122]

**Comment by Hywan** [comment]
Hello,

The best way is to visit the model (`Hoa\Ruler\Model`) and pick all [`Bag\Context` instances](https://github.com/hoaproject/Ruler/blob/master/Model/Bag/Context.php).

Do you need pointers or help?

**Comment by vucongduy1902** [comment]
Thank you very much. I got it.  :)).

**Comment by Hywan** [comment]
Feel free to get in touch with us at any moment 😃!
