### ISSUE TITLE
Removing existing operators

### ISSUE THREAD

**Issue by vicdelfant** [hoaproject/Ruler#123]
We'd like to use Ruler in a project that would ideally use localized (translated) operators to improve usability for the end-user, such as `en` for `and`, `niet` for `not` etc. This is of course possible by adding these operators to the `Asserter`, but there is no way to remove an existing operator.

Before I start working on a PR, I'd like to check whether there are any objections against an `Asserter::removeOperator($operator)` and/or `Asserter::removeOperators()` method.

**Comment by guiled** [comment]
Why don't you change the Ruler grammar ?
at these lines https://github.com/hoaproject/Ruler/blob/master/Grammar.pp#L51-L54
Changing `(?i)not\b` by `(?i)niet\b` (or maybe, whatever you want in unicode)

**Comment by vicdelfant** [comment]
Thanks! That's exactly what I was looking for.
