### ISSUE TITLE
add ability to pass operator via context

### ISSUE THREAD

**Issue by th3fallen** [hoaproject/Ruler#27]
It would be fantastic if i could pass the operator in via the context like the following example

```
    $ruleString = 'app operator value';

    $context = new Context();
    $context['app'] = $this->critera['app'];
    $context['operator'] = '!=';
    $context['value'] = $rule->value;
```

**Comment by janvandijk** [comment]
How far did you come with this use-case? I'm wanting to implement the same kind of functionality

**Comment by th3fallen** [comment]
@janvandijk see https://github.com/hoaproject/Ruler/issues/27#issuecomment-62015619 i did it using the `setOperator` method.

**Comment by janvandijk** [comment]
Awesome, I did read that comment... was wondering if there were any changes since then.

(Thank you for your reply!) :+1:
