### ISSUE TITLE
Could identifiers start with a digit?

### ISSUE THREAD

**Issue by gael-wogenstahl** [hoaproject/Ruler#32]
Bonjour,

Pour faire suite à cette discussions sur la mailing list support d'Hoa => http://lists.hoa-project.net/arc/support/2014-11/msg00004.html, je pense que la grammaire de reconnaissance des identifiants pour l'interprétation des règles peut être améliorée.

En effet, dans le cas d'identifiants commençant par un chiffre comme 1_identifiant, le premier caractère est reconnu comme un entier et le reste génère une erreur au lieu de considérer l'ensemble comme un identifiant.

J'ai trouvé une grammaire alternative qui fonctionne sans casser la détection des entiers (a vérifier sur des jeux de test plus complet cependant) qui est la suivante => \d+(?![^\s\(\)\[\],\.])

Qu'en pensez-vous ?

**Comment by gael-wogenstahl** [comment]
Hello guys, have you been thinking about this question and updating the grammar ?
I reckon those identifiers aren't allowed in other languages but one of Hoa Ruler purpose can be to simplify the writing of business rules and possibly be used by non-programming-standard-aware people. In that case (which I admit is closer to mine) it could be a limitation.

**Comment by Hywan** [comment]
I will close this issue as soon as possible, sorry for the delay :-).

**Comment by Hywan** [comment]
See #46.

**Comment by Hywan** [comment]
It will create too much conflicts and decrease performances if we implement this feature. So, unless someone finds a better solution than I did, I close this issue :-).
