### ISSUE TITLE
Introduce lazy evaluation in functions/operators

### ISSUE THREAD

**Issue by vonglasow** [hoaproject/Ruler#33]
For example, if I have a rule
```php
$rule  = 'group in ("customer", "guest") and points > 30';
```
and group is not customer neither guest we don't need to evaluate points > 30 and directly return false.

**Comment by simkimsia** [comment]
technically speaking, i think this is called boolean short circuit evaluation. Here is a stackoverflow question on this topic http://stackoverflow.com/q/1232603/80353 I think this will be a good feature especially for use cases with 1000s of rules that require assertions

**Comment by Hywan** [comment]
@simkimsia It will be enable by default ;-). Thanks for the link!

**Comment by shouze** [comment]
:+1: Woot Woot!

**Comment by vonglasow** [comment]
I think is done ;)

**Comment by Hywan** [comment]
@vonglasow Thanks for the clean up;-).
