### ISSUE TITLE
add custom alias to operators

### ISSUE THREAD

**Issue by jgoux** [hoaproject/Ruler#44]
Hello,
is it possible to add custom alias to the operators and/or for example ?
I'd like to translate them in french, so "and" would be aliased by "et" and "or" by "ou".

Thanks for this awesome piece of software. :)

**Comment by Hywan** [comment]
Hello :-),

Check this line here: https://github.com/hoaproject/Ruler/blob/master/Visitor/Asserter.php#L89. Does it help?

**Comment by jgoux** [comment]
Merci beaucoup !
