### ISSUE TITLE
Chain after a function call

### ISSUE THREAD

**Issue by jgoux** [hoaproject/Ruler#45]
Hello,
it's not possible to chain after a function call.
For example if I define a variable in the context which return an object, I'm unable to access the object's properties / functions.
This exception is thrown : 

```php
[Hoa\Compiler\Exception\UnexpectedToken]                           
Unexpected token "." (dot) at line 1 and column 46:
```

**Comment by stephpy** [comment]
Hi,

You mean `get_user(1).id` where `get_user(1)` would return a `User` instance ?

Indeed, it's not supported at this time.

**Comment by jgoux** [comment]
@stephpy Yes, exactly this.

**Comment by Hywan** [comment]
@stephpy Yup, I assign the bug to me.

**Comment by Hywan** [comment]
This issue is a little bit postponed because I would like to have better tests before. See https://github.com/hoaproject/Regex/issues/14 which is blocking to automatically generated test data for this library.
