### ISSUE TITLE
Ruler hackbook

### ISSUE THREAD

**Issue by ekoome** [hoaproject/Ruler#48]
When would the hackbook /documentation be available for HOA/Ruler?

**Comment by Hywan** [comment]
@ekoome I am currently working on it. I hope to get the documentation released in 1 or 2 months (in 2 languages).

**Comment by Hywan** [comment]
(feel free to question me; I closed the issue because I answered to your question)

**Comment by ekoome** [comment]
Do you have a draft in any language you can share? Interested in the project and keen to get started with the details.

**Comment by Hywan** [comment]
@ekoome Not yet, but watch this repository, you will receive a notification.

**Comment by Hywan** [comment]
@ekoome Track: https://github.com/hoaproject/Ruler/issues/48.
