### ISSUE TITLE
Context executing native php functions

### ISSUE THREAD

**Issue by th3fallen** [hoaproject/Ruler#50]
Per our conversation on IRC when a user uses a native php function in a rule assertion i.e. `file equals files` Ruler is actually executing the native php function `file` instead of parsing it as the string it is.

The offender you spoke of is located here
https://github.com/hoaproject/Ruler/blob/master/Context.php#L116

**Comment by Hywan** [comment]
Canonical URL: https://github.com/hoaproject/Ruler/blob/1b5083f4e2abadc8957cee9ca89f887fb2695db5/Context.php#L116.

**Comment by Hywan** [comment]
I am going to make a PR as soon as possible.

**Comment by Hywan** [comment]
New snapshot: `1.15.02.05`.
