### ISSUE TITLE
Fatal error on 'true' rule

### ISSUE THREAD

**Issue by dhaarbrink** [hoaproject/Ruler#64]
Given the following code:

    $ruler = new \Hoa\Ruler\Ruler();
    $result = $ruler->assert('true', new \Hoa\Ruler\Context());

I expect $result to equal boolean(true), but instead I get a Fatal error.
When I change the rule to 'true = true', I get the expected result. 

But the main point is that I am getting a (non catchable) fatal error from which I cannot recover. A fatal error is unacceptable to me in this context. I should always be able to recover.

**Comment by Hywan** [comment]
Please, could you test https://github.com/hoaproject/Ruler/pull/65? It fixes your issue here.

**Comment by dhaarbrink** [comment]
@Hywan, #65 does indeed fix this issue for me.

**Comment by Hywan** [comment]
This is not an important bug fix so we might wait at most 6 weeks before the next snapshot. @dhaarbrink If you need it, you can require `hoa/ruler@dev` in your `composer.json` file.

**Comment by dhaarbrink** [comment]
We're not going to production with this product for another two weeks I think. So I'd rather wait for the stable version. Thanks for the heads up though!

**Comment by Hywan** [comment]
@dhaarbrink Is it for an open source product, or something we can mention in our “hall of fame”?

**Comment by Hywan** [comment]
Anyway, thank you for the bug report!
