### ISSUE TITLE
Add an error message when we set a keyword in the context

### ISSUE THREAD

**Issue by 1e1** [hoaproject/Ruler#67]
There is no warning if we set a reserved keyword in the context. 
But we can not use it because there is no variable recognition (by escaped field or by location).

```
<?php

require __DIR__ . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

$ruler = new Hoa\Ruler\Ruler();

// New rule.
$rule  = 'points > 30 and and=1';

// New context.
$context         = new Hoa\Ruler\Context();
$context['points'] = 42;
$context['and'] = 1;

// Finally, we assert the rule.
var_dump(
    $ruler->assert($rule, $context)
);

/**
 * Will output:
 *     bool(true)
 */
```

```
PHP Fatal error:  Uncaught Hoa\Compiler\Llk\Parser::parse(): (0) Unexpected token ">" (identifier) at line 1 and column 8:
points > 30 and and=1
       ↑
in /Users/agerlier/Documents/repogit/Ruler/vendor/hoa/compiler/Llk/Parser.php at line 1.
  thrown in /Users/agerlier/Documents/repogit/Ruler/vendor/hoa/compiler/Llk/Parser.php on line 1

Fatal error: Uncaught Hoa\Compiler\Llk\Parser::parse(): (0) Unexpected token ">" (identifier) at line 1 and column 8:
points > 30 and and=1
       ↑
in /Users/agerlier/Documents/repogit/Ruler/vendor/hoa/compiler/Llk/Parser.php at line 1.
  thrown in /Users/agerlier/Documents/repogit/Ruler/vendor/hoa/compiler/Llk/Parser.php on line 1
```
Well, at the first run we know the error. 

Bug or not bug? 

If the rule is editable by an end-user, `Hoa\Ruler\Ruler::interpret($rule)` should point on the second `and` instead of `>`.

**Comment by Hywan** [comment]
@1e1 If you remove the `$context['and']` declaration, you don't have an error, correct?

**Comment by 1e1** [comment]
If I remove `$context['and'] = 1;` I have the same error. 
Declaring a `and` context is ineffective.

I have to remove `and = 1` (and the `and` operator) to prevent the error:
- `$rule  = 'points > 30';` OK
- `$rule  = 'points > 30 and 1';` OK
- `$rule  = 'points > 30 and = 1';` expected FAIL
- `$rule  = 'points > 30 and and 1';` expected FAIL
- `$rule  = 'points > 30 and and = 1';` FAIL… expected depending the context declaration

**Comment by Hywan** [comment]
Give me some days to dig a little bit please, something more important on the way :-).

**Comment by Hywan** [comment]
So, quickly. The error is not a bug, it's just the compiler that tries to find the last error. Then, … (in few minutes, I hope ;-)).

**Comment by Hywan** [comment]
And yes, we cannot use variable names that are tokens of the grammar, because tokens —by definition— are reserved. Check the grammar: https://github.com/hoaproject/Ruler/blob/1641b64fa6b40ea91ec1e129515d53fbd0d12451/Grammar.pp#L54.

**Comment by Hywan** [comment]
So… from my point of view, this is not a bug. It's like naming a class `class` in PHP. You don't want to do that, and we cannot prevent it. Well, the compiler prevents it by triggering an error.

**Comment by Hywan** [comment]
So for me, the issue is closed. Feel free to re-open or ask more details if you are not satisfied. We will be glad to answer!
