### ISSUE TITLE
invalid exampl indocumentation

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Ruler#69]
http://hoa-project.net/Fr/Literature/Hack/Ruler.html#Serialize_the_object_model

in this example we speak about $ruleId but this is not defined.

**Comment by Hywan** [comment]
@Grummfy Hello :-),

Yes, this is almost a pseudo-code. Let's suppose `$ruleId` exists, this is not important to understand the algorithm. This is an uninstanciated variable.
