### ISSUE TITLE
syntax error in a core/Consistency.php after installing with composer

### ISSUE THREAD

**Issue by abioneperhobby** [hoaproject/Ruler#76]
Hi.
I'm a newbie of composer so probably i made something wrong but after installing with composer , netbeans warned me about an error in core/Consistency.php

that is because of 

if (!function_exists('curry')) {
    function curry($callable)
    {
        $arguments = func_get_args();
        array_shift($arguments);
        $ii        = array_keys($arguments, …, true);

        return function () use ($callable, $arguments, $ii) {
            return call_user_func_array(
                $callable,
                array_replace($arguments, array_combine($ii, func_get_args()))
            );
        };
    }
}

the problem is the "..." of
$ii        = array_keys($arguments, …, true);

**Comment by abioneperhobby** [comment]
and the same file in the function curry_ref

**Comment by Hywan** [comment]
This is not an error. This is a Netbeans bug that do not support PHP syntax correctly :-).
