### ISSUE TITLE
Incorrect condition on disassembly

### ISSUE THREAD

**Issue by julban** [hoaproject/Ruler#79]
Hi all,

There is a problem in [Disassembly class](https://github.com/hoaproject/Ruler/blob/master/Visitor/Disassembly.php#L83) on the isToken condition.
Instead of adding parenthesis when using not, and, or, xor , it adds parenthesis on other operators.
Example:
- the rule I write and I expect to get after interpreting it, getting the Model and then disassembling it:
```
((age > 50 and civility = 'mr') or (age < 40 and civility = 'mrs'))
```
- the rule I currently get with hoa/ruler in version 1.15.11.09 :
```
(age > 50) and (civility = 'mr') or (age < 40) and (civility = 'mrs')
```

I guess that the isToken condition , instead of being compared to false, should be compared to true.
Modifying this condition this way, I get the expected result.

Thanks in advance :-)

**Comment by Hywan** [comment]
Hello!

Nice one :-). Can you write a PR please?

**Comment by stephpy** [comment]
Good catch. :)

**Comment by julban** [comment]
Thanks, I'll do a PR next week unless someone needs it before, anyone's free to do it so.
