### ISSUE TITLE
Match any in array?

### ISSUE THREAD

**Issue by mdewyer** [hoaproject/Ruler#84]
I have a quick question. I have a context value that is an array, and I'd like to see if any of the values within the array match the rule. For example:

    $rule = 'segment = "test"';

    $context            = new Hoa\Ruler\Context();
    $context['segment'] = array('value1','test','value3');

I know I can use:

    $rule = 'segment[1] = "test"';

To get a match, but I don't know if the "test" value will be in the array, or what key it might be at. Is there a way to check to see if any of the values within the array match?

Thanks!

**Comment by Hywan** [comment]
Yup, you can use the `in` operator. Something like `"test" in segment` might work.

**Comment by mdewyer** [comment]
Thanks! Is there a way to use the logical operators with this to see if any of the values of the context array are for example greater than the value? Ex:

`$rule = 'order_total > 15';
$context['segment'] = array(12.50,20.99,10);`

**Comment by Hywan** [comment]
Nop. But you can create your own operator very easily! See http://hoa-project.net/En/Literature/Hack/Ruler.html#Add_functions.

**Comment by mdewyer** [comment]
Ok, cool. Thanks Ivan!

**Comment by Hywan** [comment]
Feel free to re-open it if necessary!
