### ISSUE TITLE
Error "Failed to open stream hoa://Library/Ruler/Grammar.pp" wich seems related to case sensitivity

### ISSUE THREAD

**Issue by ulk200** [hoaproject/Ruler#86]
Hi,

I'm trying to use Ruler in my project, but when i "interpret" a rule, i get the following error : 
`Failed to open stream hoa://Library/Ruler/Grammar.pp`

After some debugging i found that Hoa\Protocol\Protocol is looking into two directories (at the end of the "resolve" function) :
`<my_root>/src/vendor/Hoathis/Ruler/Grammar.pp`
`<my_root>/src/vendor/Hoa/Ruler/Grammar.pp`

But the `file_exists` that comes after always returns false because composer downloaded the files in `<my_root>/src/vendor/hoa/ruler/Grammar.pp`
The directories _hoa_ and _ruler_ are lowercase

Am i missing something ?
Thank you

**Comment by Hywan** [comment]
Hello,

What versions are you using? What is the output of `composer show` please?

**Comment by ulk200** [comment]
Thank you for your answer, my composer.json is
```
{
  "require": {
    "hoa/ruler": "^2.16"
  }
}
```

`composer show` gives
```
hoa/compiler    3.16.01.14 The Hoa\Compiler library.
hoa/consistency 1.16.03.03 The Hoa\Consistency library.
hoa/event       1.16.03.15 The Hoa\Event library.
hoa/exception   1.16.01.11 The Hoa\Exception library.
hoa/file        1.16.01.15 The Hoa\File library.
hoa/iterator    2.16.03.15 The Hoa\Iterator library.
hoa/math        1.16.05.22 The Hoa\Math library.
hoa/protocol    1.16.03.07 The Hoa\Protocol library.
hoa/regex       1.16.01.15 The Hoa\Regex library.
hoa/ruler       2.16.04.06 The Hoa\Ruler library.
hoa/stream      1.16.01.14 The Hoa\Stream library.
hoa/ustring     4.16.01.11 The Hoa\Ustring library.
hoa/visitor     2.16.01.11 The Hoa\Visitor library.
hoa/zformat     1.16.03.15 The Hoa\Zformat library.
```

**Comment by ulk200** [comment]
Sorry, the problem seems to be from my own environement, i'm using the xautoload module of Drupal to load composer, but using a simple `require_once vendor/autoload.php` resolves the issue. I will look into what differs between the autoloader of xautoload and the one from composer. I will update this issue later if i find something usefull

**Comment by ulk200** [comment]
Of found it, i managed to force the `WITH_COMPOSER` constant to `true` and it solves the issue : the \Hoa\Protocol\Node\Library will do its things and not call its parent on top of the `reach` function. 
This performs some `strtolower` that where needed in my case.
What is the use case behind the `WITH_COMPOSER` constant ?

**Comment by Hywan** [comment]
The `hoa://` protocol looks for resources. It abstracts the access to resources. In case resources are installed with Composer, we need to look in very specific path (`vendor/xxx/yyy/` for the `Xxx\Yyy` library). Because Composer puts the first two elements of the path in lowercase, we have to tricky things. This is why we have the `WITH_COMPOSER` constant. It is used only in the `Hoa\Protocol` library so far if I remind correctly. It was used in our previous autoloader but it is no longer the case.

So, nop, it's not an issue with Hoa. It's just a side-effect from the ecosystem :smiley:.

Is your issue resolved? If yes, do you think it is necessary to close this issue?

**Comment by Hywan** [comment]
Oh, and the `WITH_COMPOSER` constant is set to `true` if a class from Composer is present at runtime. You did install resources/dependencies with Composer but you're not using it after that. Is it an edge case?

**Comment by ulk200** [comment]
Thank you for the explanations :)
Yes i install the resources with composer but i'm using a third party autoloader (xautoload which is a Drupal 7 module), not the one from composer.
I don't know if it's an edge case, thinking in reverse why  would an hypotetical `WITHOUT_COMPOSER` constant means that the directories be always camelcase ?
An improvement could be to separate the "downloaded_with_composer" (which sets a specific directory structure) from the "autoloaded_with_composer". Or maybe just to mention it on this page http://hoa-project.net/En/Source.html#Dependency_manager_(Composer) ?
Just to prevent someone else to face the same problem.

As for the issue yes i think you can close it. Thanks again

**Comment by Hywan** [comment]
We are discussing if we should consider this as an edge case or if this is more. Thank you for your feedback and your exemplary help. May I ask you to open an issue on [`Hoa\Protocol`](https://github.com/hoaproject/Protocol) for the sequel of this discussion please?
