### ISSUE TITLE
Is this project still actively maintained?

### ISSUE THREAD

**Issue by yellow1912** [hoaproject/Ruler#87]
It seems like there is no update in the last 6 months?

**Comment by vonglasow** [comment]
Hello, yes it's still maintained, we are focus now on PHP7.1 compatibility which is a big part of all libraries. Also we have improved and added a lot of tests. If you have a specific needed feel free to create an issue or make a Pull Request we will review it as soon as possible.

**Comment by Hywan** [comment]
@yellow1912 Hello :-), yes this library is still active. We are currently working on bringing more safety and updating performance of the underlying library, namely [`Hoa\Compiler`](http://central.hoa-project.net/Resource/Library/Compiler). This is a long-term work and from the outside it can feel like it is not active, but I can ensure you it is!

**Comment by Hywan** [comment]
@yellow1912 As @vonglasow has suggested, if you need a particular feature, please, tell us.
I let the issue open. Please, feel free to close it if the question is resolved.

**Comment by yellow1912** [comment]
I'm glad to know it is still maintained. I'm looking for a ruler lib to use and considering this one to be the strongest candidate. I checked a few issues and there are a few PRs that have not been merged for a while so I had to ask for sure. Thank you for your hardwork.
